# Generated by Django 3.0.8 on 2020-07-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eq_type', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('state', models.IntegerField()),
                ('due', models.DateField()),
                ('borrower', models.CharField(max_length=20)),
                ('remark', models.TextField()),
            ],
        ),
    ]
